import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';

const initialState = {
  selectedMemo: null,
  MemoIsOpen: false,

}
// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.

export const memoSlice = createSlice({
  name: 'memo',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    selectMemo: (state, action) => {
      state.selectedMemo = action.payload
    },
    openMemo: state => {
      state.MemoIsOpen = true;
    },
    closeMemo: state => {
      state.MemoIsOpen = false;
    }

  }
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.

});

export const { selectMemo, openMemo, closeMemo } = memoSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectOpenMemo = (state) => state.memo.selectedMemo;
export const selectMemoIsOpen = (state) => state.memo.MemoIsOpen;
export default memoSlice.reducer;
